[tool.poetry]
name = "humble-lister"
version = "0.1.0"
description = ""
authors = ["nzdjb <github@2a1b.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
